### PR TITLE
fix(ui): avoid empty div when there are no `externalDocs`

### LINKED ISSUE #7996: Tag Description awkwardly constrained when there is no `externalDocs` entry
### Q&A (please complete the following information)
 - OS: macOS v 11.6.2
 - Browser: Firefox developer v 99.0b3 
 - Version: swagger-ui v 4.10.3
 - Method of installation: installed as npm dependency 
 - Swagger-UI version: 4.10.3
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
If `tags` -> `description` is on the lengthy side and there are no `externalDocs` associated with that tag, we end up with the lengthy description squeezed into one side of the operations tag UI. See the `store` section towards the bottom of the next screenshot.

Screenshot 2022-04-25 at 16 51 52

It would be preferable if lengthy descriptions could fill the whole container when there are no `externalDocs` entries. See the `store` section in the next screenshot.

Screenshot 2022-04-26 at 12 57 02

Note that the `pet` section contains an entry for `externalDocs` so it's description is still constrained.

Example Swagger/OpenAPI definition:
```yaml
swagger: "2.0"
info:
  description: "This is an example highlighting a display issue related to `tags` and `description` entries therein. It is based on the sample server Petstore server.  You can find out more about the original     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "pet"
  description: "Everything about your Pets. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Petstore orders. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
...
```

Swagger-UI configuration options:
_defaults_

### Describe the bug you're encountering
`tag` `description` is artificially constrained when `externalDocs` entry is not present

### To reproduce...

1. Modify Swagger/OpenAPI definition as above sample, namely extend `tag` `description` to paragraph length where there is no `externalDocs` entry
2. Run swagger-ui
3. Observe `description` constrained to left side of UI while right side is empty

### Expected behavior
It would be preferable for `description` to flow into right side of UI as well

### PR DESCRIPTION
**Pull request by matyjas**
Relocate `div` for `externalDocs` into conditional checking for existence of `externalDocs` entry.

### Description

- Move div into the conditional
- Ran `prettier` on the file

### Motivation and Context

Fixes #7996 

### How Has This Been Tested?

Manually tested on macOS with and without `externalDocs`

### Screenshots (if appropriate):

Screenshot 2022-04-26 at 12 57 02

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@matyjas Thanks for the PR! Looks goo to me, though could you add a Cypress test or two that compares and verifiies the two cases as noted in your screenshot?

**Comment by tim-lai** [comment]
related to PR #7559

File: src/core/components/operation-tag.jsx [hunk 1]
```diff
@@ -72,48 +72,49 @@ export default class OperationTag extends React.Component {
...
             <small>
-                <Markdown source={tagDescription} />
-              </small>
-            }
+              <Markdown source={tagDescription} />
+            </small>
+          }
 
+          {!tagExternalDocsDescription ? null :
             <div>
```
Comment (tim-lai) [inline src/core/components/operation-tag.jsx:92]: Let's add a className="info__externaldocs" to this div. This would enable easier Cypress assertion if the div exists. Also helps identify that this may refactored in the future into its own component.

**Review by tim-lai — CHANGES_REQUESTED** [review]

File: src/core/components/operation-tag.jsx (hunk 1 above)
Comment (matyjas) [reply src/core/components/operation-tag.jsx:92]: Thanks, that will make testing much cleaner!

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@matyjas PR merged! Thanks for the fix!
