### PR TITLE
fix: curlify agnostic to order of header values

### LINKED ISSUE #6082: FileUpload changes in generated curl request when adding a header using requestInterceptor
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)
 - Method of installation: dist assets
 - Swagger-UI version: 3.10.0 (I've tried several versions and it happens with them all)
 - Swagger/OpenAPI version: Swagger 2.0 (Happens with both Swagger 2.0 and OpenAPI 3.0)

### Content & configuration
I created an example project on github to demonstrate the issue. https://github.com/mike2184/swagger-ui-test
Swagger UI hosted on GItHub pages here: https://mike2184.github.io/swagger-ui-test/#/pet/uploadFile

Example Swagger/OpenAPI definition:
I'm using https://petstore.swagger.io/v2/swagger.json in the example I created to show this issue.

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
				url : "./swagger.yaml",
				dom_id : '#swagger-ui',
				deepLinking : true,
				presets : [ SwaggerUIBundle.presets.apis,
						SwaggerUIStandalonePreset ],
				plugins : [ SwaggerUIBundle.plugins.DownloadUrl ],
				layout : "StandaloneLayout",
				requestInterceptor : function(req) {
					// Having the following line of code that adds a header causes the generated curl request to change from
					// -F "file=@cake.jpg;type=image/jpeg" to -d {"file":{}}
					req.headers['x-test-header'] = 'test value'; 
					return req;
				}
			})
```

### Describe the bug you're encountering
If I make any changes to the headers using the requestInterceptor it changes the file upload in the generated curl request from -F "file=@cake.jpg;type=image/jpeg" to -d {"file":{}}

### To reproduce...

1. Go to https://mike2184.github.io/swagger-ui-test/#/pet/uploadFile
2. Click Try it out for /pet/{petId}/uploadImage API
3. Set petId to 1
4. Click choose file and select any image file
5. Click execute
6. Notice: generated curl request has -d {"file":{}} instead of -F "file=@cake.jpg;type=image/jpeg"

### Expected behavior
Generated curl request should be -F "file=@cake.jpg;type=image/jpeg"

### Screenshots
Screen Shot 2020-06-04 at 8 50 24 AM

### PR DESCRIPTION
**Pull request by tim-lai**
### Description

In `curlify`, the `type` would overwrite the string value to the latest header value. In the case of using `requestInterceptor` that appends a header, the final string would be whatever was provided by the `requestInterceptor`.

This fix will try to update `isMultipartFormDataRequest` until it is `true`.

This change also reorganizes and fixes the linting in the `curlify` test file

### Motivation and Context

Fixes #6082

### How Has This Been Tested?

New mocha tests that places leading/trailing custom header. There already exists a mocha test with no custom header. Note, although the term `custom` is used, any header and order should not impact the curlify result.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

File: test/mocha/core/curlify.js [hunk 1]
```diff
@@ -194,6 +194,54 @@ describe("curlify", function() {
         expect(curlified).toEqual("curl -X POST \"http://example.com\" -H  \"content-type: multipart/form-data\" -F \"id=123\" -F \"file=@file.txt;type=text/plain\"")
     })
 
+    it("should print a curl with formData and file, and trailing custom header", function () {
```
Comment (char0n) [inline test/mocha/core/curlify.js:197]: Mocha allows us to structure tests into logical groups by using `context/specify` aliases.
```js
context('given request with multipart/form-data content type and file', function () {
  context('and trailing custom header', function() {
    specify('should print a proper curl', function () {
      ...test..
    });
  });

  context('and leading custom header', function() {
    specify('should print a proper curl', function () {
      ...test..
    });
  });
});

File: test/mocha/core/curlify.js [hunk 2]
```diff
@@ -194,6 +194,54 @@ describe("curlify", function() {
...
+        // use case: requestInterceptor appends req.headers as trailing header
```
Comment (char0n) [inline test/mocha/core/curlify.js:198]: Shouldn't use comments, unless absolutely necessary. Everything should be translated into test descriptions.

File: test/mocha/core/curlify.js [hunk 3]
```diff
@@ -194,6 +194,54 @@ describe("curlify", function() {
...
+            }
+        }
+
+        let curlified = curl(Im.fromJS(req))
+
+        expect(curlified).toEqual("curl -X POST \"http://example.com\" -H  \"content-type: multipart/form-data\" -H  \"x-custom-name: any-value\" -F \"id=123\" -F \"file=@file.txt;type=text/plain\"")
+    })
+
+    it("should print a curl with formData and file, and leading custom header", function () {
+        // confirm leading custom header order is also valid, and does not impact -F
```
Comment (char0n) [inline test/mocha/core/curlify.js:222]: Shouldn't use comments, unless absolutely necessary. Everything should be translated into test descriptions.

If we're testing for another aspect of generated curt, we should have a separate test for it.

File: src/core/curlify.js [hunk 4]
```diff
@@ -25,15 +25,14 @@ export default function curl( request ){
...
+      headerValues[v] = h
       curlified.push( "-H " )
       curlified.push( `"${h}: ${v}"` )
     }
   }
 
   if ( request.get("body") ){
-
-    if(type === "multipart/form-data" && ["POST", "PUT", "PATCH"].includes(request.get("method"))) {
+    if (headerValues["multipart/form-data"] && ["POST", "PUT", "PATCH"].includes(request.get("method"))) {
```
Comment (char0n) [inline src/core/curlify.js:35]: The code itself has an obvious bug, demonstrated by following non-failing test case:
```js
context('given request with Authorization header of multipart/form-data value', function () {
  specify('should not consider request multipart', function () {
    let file = new win.File()
    file.name = "file.txt"
    file.type = "text/plain"

    let req = {
      url: "http://example.com",
      method: "POST",
      headers: {
        "Authorization": "multipart/form-data",
        "x-custom-name": "any-value"
      },
      body: {
        id: "123",
        file
      }
    }
  
   let curlified = curl(Im.fromJS(req))
    ...what are we expecting here...?
});

File: test/mocha/core/curlify.js [hunk 5]
```diff
@@ -194,6 +194,54 @@ describe("curlify", function() {
         expect(curlified).toEqual("curl -X POST \"http://example.com\" -H  \"content-type: multipart/form-data\" -F \"id=123\" -F \"file=@file.txt;type=text/plain\"")
     })
 
+    it("should print a curl with formData and file, and trailing custom header", function () {
+        // use case: requestInterceptor appends req.headers as trailing header
+        var file = new win.File()
```
[the remark this answers is not in the document]
Comment (tim-lai) [reply test/mocha/core/curlify.js:199]: legacy cleanup required.

**Comment by tim-lai** [comment]
@char0n Updated. Please take another look. Thanks!

File: src/core/curlify.js [hunk 6]
```diff
@@ -25,15 +25,18 @@ export default function curl( request ){
   if ( headers && headers.size ) {
     for( let p of request.get("headers").entries() ){
       let [ h,v ] = p
-      type = v
       curlified.push( "-H " )
       curlified.push( `"${h}: ${v}"` )
+      if (isMultipartFormDataRequest) {
```
Comment (char0n) [inline src/core/curlify.js:30]: Why do we have this condition here? If the request is considered as multipart request I still want to process other headers and not ignore them. This condition effectively does that. Is that something you intended? If yes, why ?

File: test/mocha/core/curlify.js [hunk 7]
```diff
@@ -3,247 +3,335 @@ import Im from "immutable"
 import curl from "core/curlify"
 import win from "core/window"
 
-describe("curlify", function() {
```
Comment (char0n) [inline test/mocha/core/curlify.js:6]: @tim-lai you should never do refactors inside bug fixes. At this point from this PR I cannot identify tests that are related to this fix. I'd suggest you revert the changes back and only fix/create relevant tests for this bug fix. Other refactoring should be part of different PR.

File: test/mocha/core/curlify.js [hunk 8]
```diff
@@ -3,247 +3,335 @@ import Im from "immutable"
...
-                status: "available"
-            },
-            headers: {
-                Accept: "application/json",
-                "content-type": "application/json"
-            }
+describe("curlify", function () {
+  context("POST", function () {
+    it("prints a curl statement with custom content-type", function () {
+      const req = {
```
Comment (char0n) [inline test/mocha/core/curlify.js:9]: You're using `const` instead of `let` in this file. The convention of this project is to use and prefer `let` instead of `const`. I don't agree with this convention, but nevertheless it's a convention and unless we change this convention globally we should adhere to it. Consistency is one of the most important aspect of code and without adhering to conventions we can never have consistency.

File: src/core/curlify.js [hunk 9]
```diff
@@ -25,15 +25,18 @@ export default function curl( request ){
...
+        break
+      } else {
+        isMultipartFormDataRequest = /content-type/i.test(h) && /multipart\/form-data/i.test(v)
```
Comment (char0n) [inline src/core/curlify.js:33]: Actually I did a mistake in regex definition here
```suggestion
        isMultipartFormDataRequest = /^content-type$/i.test(h) && /^multipart\/form-data$/i.test(v)
```
Regex should be fined as exact match

File: src/core/curlify.js (hunk 6 above)
Comment (tim-lai) [reply src/core/curlify.js:30]: @char0n This is intentional. After initialization, we only want to set this flag once (to true). If you don't `break`, it will overwrite again, possibly as false, which then fails test.

File: test/mocha/core/curlify.js (hunk 7 above)
Comment (tim-lai) [reply test/mocha/core/curlify.js:6]: reverted refactor. left in fixes for var/let/const/spaces

File: src/core/curlify.js (hunk 6 above)
Comment (char0n) [reply src/core/curlify.js:30]: Regarding the break stetement: https://github.com/swagger-api/swagger-ui/pull/6152/files#r442378491

You're right in the fact that signal variable will be overridden to false by subsequent loop. Good catch!
But this implementation will stop the loop for good and curlified array will not be filled with additional headers that needs transformation to curl form.
IMHO correct implementation without introducing additional problems would be :

```js
isMultipartFormDataRequest = isMultipartFormDataRequest || /^content-type$/i.test(h) && /^multipart\/form-data$/i.test(v)
```

File: test/mocha/core/curlify.js [hunk 10]
```diff
@@ -246,4 +246,77 @@ describe("curlify", function() {
...
+                        "x-custom-name": "multipart/form-data",
+                        "content-type": "multipart/form-data"
+                    },
+                    body: {
+                        id: "123",
+                        file
+                    }
+                }
+
+                const curlified = curl(Im.fromJS(req))
```
Comment (char0n) [inline test/mocha/core/curlify.js:269]:
```suggestion
                let curlified = curl(Im.fromJS(req))
```

File: test/mocha/core/curlify.js [hunk 11]
```diff
@@ -246,4 +246,77 @@ describe("curlify", function() {
...
+                url: "http://example.com",
+                method: "POST",
+                headers: { "x-custom-name": "multipart/form-data" },
+                body: {
+                    id: "123",
+                    file
+                }
+            }
+
+            const curlified = curl(Im.fromJS(req))
```
Comment (char0n) [inline test/mocha/core/curlify.js:317]:
```suggestion
            let curlified = curl(Im.fromJS(req))
```

File: test/mocha/core/curlify.js [hunk 12]
```diff
@@ -246,4 +246,77 @@ describe("curlify", function() {
...
+                        "content-type": "multipart/form-data",
+                        "x-custom-name": "any-value"
+                    },
+                    body: {
+                        id: "123",
+                        file
+                    }
+                }
+
+                const curlified = curl(Im.fromJS(req))
```
Comment (char0n) [inline test/mocha/core/curlify.js:294]:
```suggestion
                let curlified = curl(Im.fromJS(req))
```
