### PR TITLE
fix: object parameter validation

### LINKED ISSUE #5581: v3.23.7 breaks try-it-out on POST method
### Q&A (please complete the following information)
 - OS: [e.g. Linux Debian testing]
 - Browser: [Chromium]
 - Version: [76.0.3809.100]
 - Method of installation: [dist assets]
 - Swagger-UI version: [v3.23.7]
 - Swagger/OpenAPI version: [Swagger 2.0]

### Content & configuration

Just http://petstore.swagger.io/

Example Swagger/OpenAPI definition:

https://petstore.swagger.io/v2/swagger.json

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

The execute button on POST method doesn't trigger an HTTP request

### To reproduce...

1. Open http://petstore.swagger.io/#/store/placeOrder
2. Click "Try it out"
3. Click "Excute"

### Expected behavior

An HTTP request is sent

This works on v3.23.6

### Screenshots
image

### PR DESCRIPTION
**Pull request by shockey**
Fixes #5581 .

Curiously, before #5571, runtime validation was failing open for all body parameters. Solving that issue in #5571 exposed a flaw in validating required `type: object` values in 2.0, which we deal with here.

### CODE REVIEW

File: src/core/utils.js [hunk 1]
```diff
@@ -527,31 +528,23 @@ export const validateParam = (param, value, { isOAS3 = false, bypassRequiredChec
...
-      //     JSON.parse(value)
-      //     oas3ObjectCheck = true
-      //   } catch(e) {
-      //     errors.push("Parameter string value must be valid JSON")
-      //     return errors
-      //   }
-      // }
-    }
+    let objectCheck = type === "object" && typeof value === "object" && value !== null
+    let objectStringCheck = type === "object" && typeof value === "string" && value
```
Comment (shockey) [inline src/core/utils.js]: Object values are commonly JSON/XML strings, which we need to accommodate for.
