### PR TITLE
clears authentications when logout is clicked

### LINKED ISSUE #4641: The Logout button in Authorize popup not clearing API Key
### Q&A (please complete the following information)
 - OS: Windows 8.1
 - Browser: Opera, Chrome, Firefox
 - Version: 53.0.2907.68
 - Method of installation: in Demo at [http://petstore.swagger.io](http://petstore.swagger.io)

### Describe the bug you're encountering
The Authorize Popup is not clearing the apiKey when LogOut button is clicked.

### To reproduce...

1. Go to [http://petstore.swagger.io](http://petstore.swagger.io)
2. Click on the Authorize popup
3. Scroll down to the API key section
4. Type a text in the textbox
5. Click on Authorize
6. Without closing the Popup, click on Logout and again Authorize.
7. The APIKey is authorized even though there is nothing in the textbox

### Expected behavior
It shouldn't allow to authorize an empty textbox

### Screenshots
authorize

### LINKED ISSUE #4904: Authorization is possible after logging out in the popup
the bug is easily producible from : https://petstore.swagger.io/

- fill the value with token then authorize
- click logout
- click authorize without putting any token (leaving value empty), still able to authorize

### PR DESCRIPTION
**Pull request by leggsimon**
### Description
This PR allows a user to “log out” and the app forgets the state of their previously used api keys.

### Motivation and Context

Fixes #4641. Fixes #4904. 

When the logout button is clicked in the authorise popup the request was being made to the redux store to clear the key. However if the user clicked “Authorise” it sends what ever is in the component’s state and populates the redux store with that. Since, on logout, the state in the component wasn’t being cleared if you just clicked “Authorise” it would resend the same value it had before logging out.

### How Has This Been Tested?
Manually as well as adding 2 cypress tests to cover the “normal” user journey and the new bug. I ensured that the tests failed before putting in my fix.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests. **To my knowledge I can’t think of any but am happy to add more**
- [ ] All new and existing tests passed.

### CODE REVIEW

File: test/e2e-cypress/tests/bugs/4641.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
+describe("#4641: The Logout button in Authorize popup not clearing API Key", () => {
```
Comment (shockey) [inline test/e2e-cypress/tests/bugs/4641.js]: I'd like to see a third test case that covers the following scenario.

Given this definition:

```yaml
openapi: 3.0.0
paths:
  /:
    get:
      description: ok
      security:
      - securityA: []
      - securityB: []
      responses: 
        200: 
          description: ok
components:
  securitySchemes:
    securityA:
      type: apiKey
      name: SecurityA
      in: header
    securityB:
      type: apiKey
      name: SecurityB
      in: header
```

1. I authorize securityA and securityB.
2. I logout and then attempt to reauthorize securityB (idea being: the data will be blank, so reauthorization won't happen).
3. I execute my operation.
4. **Assert that securityA was attached to the request, and securityB was not.**

My rationale here is that the data-clearing code is in the Auths component, which has the capability to wipe out more than one authorization's data, so we should have a defensive test against that happening.

File: test/e2e-cypress/static/documents/bugs/4641.yaml [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+info:
+  title: Demo API
+  description: First test
+  termsOfService: 'http://demo.io/terms-of-service/'
+  contact:
+    name: Demo Support
+    email: support@demo.io
+  version: 1.0.0
+servers:
+  - url: 'https://httpstat.us/'
```
Comment (shockey) [inline test/e2e-cypress/static/documents/bugs/4641.yaml]: Cypress tests need to avoid relying on external services - if `httpstat.us` is ever offline, this test will fail because Swagger UI will show `TypeError: failed to fetch` instead of the response content.

If you just drop the `servers` block, the request will just hit the test server and you'll get back a 404, which should work for your purposes since you only care about what's in the request 😄

**Comment by leggsimon** [comment]
Cool, that sounds totally reasonable. Didn’t know you could do that, I’ll update them

**Comment by leggsimon** [comment]
@shockey I’ve added a new test based on your suggestion and also changed the tests so that it’s checking the request headers being sent (this is also way faster).

I’ve also refactored these tests slightly to extract some of the common things like filling out the auth field and clicking authenticate. Personally I think it’s slightly more readable but am happy to change it back. I know it’s not everyones cup of tea.

File: test/e2e-cypress/static/documents/bugs/4641.yaml (hunk 2 above)
Comment (leggsimon) [reply test/e2e-cypress/static/documents/bugs/4641.yaml]: done in 3ef208e

File: test/e2e-cypress/tests/bugs/4641.js [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+      .click()
+      .get(".opblock-summary") // expand the route details
+      .click()
+      .get(".try-out > .btn") // expand "try it out"
+      .click()
+      .get(".execute-wrapper > .btn") // excecute request
+      .click()
+      .wait(2000) // wait for response
+      .get(".curl")
+      .should("contain", "api_key: my_api_key")
```
[the remark this answers is not in the document]
Comment (leggsimon) [reply test/e2e-cypress/tests/bugs/4641.js]: done in 3ef208e

File: test/e2e-cypress/tests/bugs/4641.js (hunk 1 above)
Comment (leggsimon) [reply test/e2e-cypress/tests/bugs/4641.js]: done in a0b8f4f

**Comment by leggsimon** [comment]
@shockey any possibility of a re-review?

File: test/e2e-cypress/tests/bugs/4641.js [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+      .get("#operations-default-get_4641_1") // expand the route details
+      .within(clickTryItOutAndExecute)
+      .get("@request")
+      .its("request")
+      .should(request => {
+        expect(request.headers).not.to.have.property("api_key_1")
+      })
+  })
+
+  it("should not only forget the value of the auth the user logged out from", () => {
```
Comment (shockey) [inline test/e2e-cypress/tests/bugs/4641.js]:
```suggestion
  it("should only forget the value of the auth the user logged out from", () => {
```

**Comment by leggsimon** [comment]
Appreciate it

**Comment by shockey** [comment]
thanks for the contribution, @leggsimon!
