### PR TITLE
fix(json-schema-2020-12): Fix OAS 3.1 additionalProperties false samples

### LINKED ISSUE #9022: OpenAPI 3.1.0 support: `additionalProperties: false` adds `additionalProp1` to samples
### Q&A
 - OS: macOS
 - Browser: chrome
 - Version: Version 114.0.5735.198 (Official Build) (arm64)
 - Method of installation: git & npm
 - Swagger-UI version: [v5.1.1](https://github.com/swagger-api/swagger-ui/tree/v5.1.1)/[`89f04d3`](https://github.com/swagger-api/swagger-ui/tree/89f04d3f11288b4a63bf1f6dda3a7ca297ed69ff) (latest master)
 - Swagger/OpenAPI version: OpenAPI 3.1.0 - Not an issue in OpenAPI 3.0.x

#### Example OpenAPI definition
Minimal example that demonstrates the issue for `"additionalProperties": false` with OpenAPI 3.1.0 
```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "foo",
    "version": "0.1.0"
  },
  "paths": {
    "/": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "bar": {
                    "type": "string"
                  }
                },
                "additionalProperties": false,
                "type": "object",
                "title": "Foo"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response"
          }
        }
      }
    }
  }
}
```

### Describe the bug you're encountering
When the value of `openapi` in the OpenAPI definition is `3.0.3`, the sample body for a `POST /` request is correctly rendered as
```json
{
  "bar": "string"
}
```

However, when the value of `openapi` is `3.1.0`, the sample body for a `POST /` request is incorrectly rendered as
```json
{
  "bar": "string",
  "additionalProp1": {}
}
```

### To reproduce...

1. Follow the instructions in https://github.com/swagger-api/swagger-ui/blob/master/docs/development/setting-up.md#steps to set up dev environment
2. Save the above OpenAPI definition to `dev-helpers/examples/openapi.json`
3. Follow the instructions in https://github.com/swagger-api/swagger-ui/blob/master/docs/development/setting-up.md#using-your-own-local-api-definition-with-local-dev-build to modify `dev-helpers/dev-helper-initializer.js` by replacing `https://petstore.swagger.io/v2/swagger.json` with `./examples/openapi.json`
4. Go to http://localhost:3200/ in browser
5. See error in sample request body: `additionalProp1` field is present, violating `"additionalProperties": false` in OpenAPI definition

Modifying the value of `openapi` to `3.0.3` (or any existing 3.0.x version) in `dev-helpers/examples/openapi.json` will display a correct sample.

### Expected behavior
The sample request body for OpenAPI 3.1.0+ should not generate additional properties when `"additionalProperties": false` is present, instead maintaining consistency with OpenAPI 3.0.x samples.

### Screenshots

Correct sample with OpenAPI 3.0.3:
image

Incorrect sample with OpenAPI 3.1.0:
image

### Additional context or thoughts

Introduced in the implementation of #8577 in the PR #8910 in 
`src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js`
with change from `if (additionalProperties === true) {` to `if (isBooleanJSONSchema(additionalProperties)) {`.

### PR DESCRIPTION
**Pull request by adavis444**
### Description

swagger-ui incorrectly adds `"additionalProp1": {}` to samples for schemas where `additionalProperties` is `false` in OpenAPI 3.1.0, even though this was previously correct in OpenAPI 3.0.x.

This fixes a change in #8910 that did not handle the case that `additionalProperties` is `false`, which broadened the condition `additionalProperties === true` to `isBooleanJSONSchema(additionalProperties)` with the same handling, treating an `additionalProperties` value of `false` identically to a value of `true`.

This can be remedied by changing `isBooleanJSONSchema(additionalProperties)` to `isBooleanJSONSchema(additionalProperties) && additionalProperties === true`.

This restores some parity between `src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js` and `src/core/plugins/samples/fn/index.js`.

### Motivation and Context

No additional properties should be added to samples for schemas where `additionalProperties` is `false`, maintaining consistency with the behavior in OpenAPI 3.0.x.

Fixes #9022

Refs #8577

### How Has This Been Tested?

Following the steps in "To reproduce..." in #9022 using that `openapi.json` example, on master we have a sample body for a `POST /` request of
```json
{
  "bar": "string",
  "additionalProp1": {}
}
```

On this branch, it is
```json
{
  "bar": "string"
}
```

I've added identical tests to `test/unit/core/plugins/samples/fn/index.js` and to `test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js`.

However, as seen in the [unit test results](https://github.com/adavis444/swagger-ui/actions/runs/5569343439/jobs/10172617804?pr=2) when [tests are added without code changes](https://github.com/adavis444/swagger-ui/pull/2), on master it is expected that the tests for `test/unit/core/plugins/samples/fn/index.js` will pass whereas the tests for `test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js` will fail.

### Screenshots (if appropriate):

On master
image

On this branch
image

### My PR contains...

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...

- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation

- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests

- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by char0n** [comment]
Hi @adavis444,

Thanks for the PR! We'll get to this PR probably during Thursday this week.

**Review by char0n — APPROVED** [review]
LGTM! Thanks for contributing! I'll make some additional nitpick changes to this PR before the merge.

File: src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js [hunk 1]
```diff
@@ -420,7 +420,10 @@ export const sampleFromSchemaGeneric = (
       return res
     }
 
-    if (isBooleanJSONSchema(additionalProperties)) {
+    if (
+      isBooleanJSONSchema(additionalProperties) &&
+      additionalProperties === true
```
Comment (char0n) [inline src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js:425]: no need for `additionalProperties === true`. We can simplify to

```js
if (isBooleanJSONSchema(additionalProperties) && additionalProperties) {
```
