### PR TITLE
fix: preserve multipart file part position in requestData

### LINKED ISSUE #6979: Element defined as type = "string", format = "binary" gets passed always as the last element in a multipart/form-data?
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: N/A
 - Method of installation: Via the usage of Swashbuckle.AspNetCore
 - Swagger-UI version: 3.42.0
 - Swagger/OpenAPI version: Swagger 3.0, OpenAPI 3.0
---

As per OpenAPI 3.0 specifications, there is no longer a type "file", but instead, we should define files using the type string and a format either binary, or byte. (Source: https://swagger.io/docs/specification/data-models/data-types/)

When we define a multipart/form-data content, which includes several properties, one of which is a file, if that file is defined in any order, using the legacy 2.0 approach - it gets fed in the order of which it was defined when reading the underlying form data stream. (expected result)

But when it is defined in the new 3.0 convention, for some reason, the data to the server is passed in a way that it is always the last element in the multipart/form-data, regardless in what order the file was defined.

Meaning if we had a single file, and 3 other properties of any other type,, the file would always be the last one to be read in the multipart/form-data request.

Is this a feature? If so, why the subtle differences?

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

when providing type string format binary aka file position is not preserved,
because it is not registered on component mount like all others do.
So the state is later on corrupted,
because when the file is set and so a new property will be added to requestData Map in state.
This results in beeing the last property.
since all other properties' components are registering their value on component mount,
the oder is preserved for those.

Signed-off-by: mathis-m <mathis.michel@outlook.de>

### Motivation and Context

Fixes #6979

### How Has This Been Tested?

http://localhost:3200/?url=https://gist.githubusercontent.com/mathis-m/33cfc17fe6e4057702f39651c7aec510/raw/8de7e798e5482069faad5d0595056629810181e7/aUf3bOBB9g.txt

### Screenshots (if appropriate):

image

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/core/json-schema-components.jsx [hunk 1]
```diff
@@ -40,6 +40,8 @@ export class JsonSchemaForm extends Component {
     const { dispatchInitialValue, value, onChange } = this.props
     if(dispatchInitialValue) {
       onChange(value)
+    } else if(dispatchInitialValue === false) {
```
Comment (tim-lai) [inline src/core/json-schema-components.jsx:43]: is this required: `if(dispatchInitialValue === false)`. If not, we could just use else { ... }. Or more node-style, 
```
if (!dispatchInitialValue) {
...new 
return 
}
...ori
```

Comment (mathis-m) [reply src/core/json-schema-components.jsx:43]: yes this is required since dispatchInitialValue is oas3 specific and in case of <oas3(body param) it will not be provided.

Comment (mathis-m) [reply src/core/json-schema-components.jsx:43]: In addition to that there were several failing tests that indicated that when using else there is something wrong.

**Comment by tim-lai** [comment]
@mathis-m PR merged! Thanks for the fix! Also, that's an interesting tidbit about `dispatchInitialValue`.
