### PR TITLE
Fix #8217: Reset Request Body not using default values

### LINKED ISSUE #8217: Cannot pass the required validation of the field which has default value after the Reset button pushed
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 106.0.5249.91 (Official Build) (arm64)
 - Method of installation: npm
 - Swagger-UI version: 4.14.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Swagger Petstore
  version: 1.0.0
tags:
  - name: pet
    description: Everything about your Pets
paths:
  /pet:
    post:
      tags:
        - pet
      operationId: addPet
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BodyParameter'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
components:
  schemas:
    BodyParameter:
      required:
        - bodyParameter
      type: object
      properties:
        bodyParameter:
          type: string
          default: default
```

Swagger-UI configuration options:
```js
window.onload = function() {
  window["SwaggerUIBundle"] = window["swagger-ui-bundle"]
  window["SwaggerUIStandalonePreset"] = window["swagger-ui-standalone-preset"]
  // Build a system
  const ui = SwaggerUIBundle({
    url: "./test.yaml",
    dom_id: "#swagger-ui",
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    // requestSnippetsEnabled: true,
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
```

### Describe the bug you're encountering

I cannot pass a required validation of the field which has a default value after clicking the Reset button

### To reproduce...
1. push `Try it out`
2. edit Request Body parameter
3. push `Reset`
4. push `Execute`
5. see validation error although the input field is reseted and has default value

### Expected behavior

pass the validation

### Screenshots

swagger-request-body

### PR DESCRIPTION
**Pull request by MathiasSpanhove**
### Description
It was not possible to pass a required validation of a request body field which has a default value after clicking the Reset button.
Behind the scenes everything was being reset to 'null' values. This fix should resolve this issue by using the default request body values instead. 

### Motivation and Context
Fixes #8217

### How Has This Been Tested?
Manually tested, please guide me on how I can test this if needed/possible. 
I did not find a related test and I'm not sure how to test this using e2e.

### Screenshots (if appropriate):
See Issue #8217

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes. **(Not sure about this one)**

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/core/components/parameters/parameters.jsx [hunk 1]
```diff
@@ -161,7 +161,10 @@ export default class Parameters extends Component {
               enabled={tryItOutEnabled}
               onCancelClick={this.props.onCancelClick}
               onTryoutClick={onTryoutClick}
-              onResetClick={() => oas3Actions.setRequestBodyValue({ value: undefined, pathMethod })}/>
+              onResetClick={() => {
```
Comment (tim-lai) [inline src/core/components/parameters/parameters.jsx:164]: These two "internal" functions should be extracted a separate "onResetClick" prop function.

File: src/core/plugins/oas3/selectors.js [hunk 2]
```diff
@@ -61,6 +61,26 @@ export const shouldRetainRequestBodyValue = onlyOAS3((state, path, method) => {
   }
 )
 
+export const defaultRequestBodyValue = (state, path, method) => (system) => {
```
Comment (tim-lai) [inline src/core/plugins/oas3/selectors.js:64]: should rename function to 'getDefaultRequestBodyValue'

**Review by tim-lai — CHANGES_REQUESTED** [review]
Thanks for the PR! Just some reorganizing changes requested.

File: src/core/plugins/oas3/selectors.js (hunk 2 above)
Comment (MathiasSpanhove) [reply src/core/plugins/oas3/selectors.js:64]: If I rename this function it will class with the already existing 'getDefaultRequestBodyValue' from "./components/request-body". May I also ask for the reason why this needs to have the 'get' prefix since the requestBodyValue function a few lines above it doesn't seem to have it either? Not sure what the naming conventions are.

File: src/core/components/parameters/parameters.jsx (hunk 1 above)
Comment (MathiasSpanhove) [reply src/core/components/parameters/parameters.jsx]: Refactored into a prop

**Comment by MathiasSpanhove** [comment]
> @MathiasSpanhove Thanks for the PR! I think the easiest path for testing is a Cypress test. E.g. in the original issue, assert that the field value is what it should be instead of "default".

I've added a Cypress test to the PR

File: src/core/plugins/oas3/selectors.js (hunk 2 above)
Comment (tim-lai) [reply src/core/plugins/oas3/selectors.js:64]: Good catch. Let's go with `selectDefaultRequestBodyValue` instead. Using `select<MethodName>` will be more inline with forward-looking naming conventions and reflective that it is a selector. As an example, using `select<MethodName>` is already used as the naming convention in swagger-editor@next.

Comment (MathiasSpanhove) [reply src/core/plugins/oas3/selectors.js]: I've renamed it into `selectDefaultRequestBodyValue`. That should cover everything for this PR, let me know if anything else needs to be changed!

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@MathiasSpanhove PR merged! Thanks for the contribution and iteration!
