### PR TITLE
Ft/value retainer sample gen

### LINKED ISSUE #6918: Multiple example rendering wrong escaped => "123" is 123
I am analyzing this currently. Looks like the internal example generator generates the correct example but within the ui components in case of multiple examples (possibly ExampleValueRetainer) the value is being wrongly stored due to back and forth Immutable.js <-> js.

_Originally posted by @mathis-m in https://github.com/swagger-api/swagger-ui/issues/5528#issuecomment-775296443_

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

This will fix issues with escaping string type // number examples in case of multiple examples.
Because it now relies on sample-gen, instead of passing raw examples to retainer now the samplegen example values are passed instead. 
I also fixed a bug where multiple example had same value and it selected every time the first one if it was change to some of the example with same value, never the less which one was selected.

### Motivation and Context

Fixes #6918 
Part of fixing #6470

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: src/core/plugins/oas3/components/request-body.jsx [hunk 1]
```diff
@@ -83,7 +83,20 @@ const RequestBody = ({
 
   const mediaTypeValue = requestBodyContent.get(contentType, OrderedMap())
   const schemaForMediaType = mediaTypeValue.get("schema", OrderedMap())
-  const examplesForMediaType = mediaTypeValue.get("examples", null)
+  let examplesForMediaType = mediaTypeValue.get("examples", null)
```
Comment (tim-lai) [inline src/core/plugins/oas3/components/request-body.jsx:86]: We should keep this as const

File: src/core/plugins/oas3/components/request-body.jsx [hunk 2]
```diff
@@ -83,7 +83,20 @@ const RequestBody = ({
...
+  if(examplesForMediaType) {
+    examplesForMediaType = examplesForMediaType.map((container, key) => {
```
Comment (tim-lai) [inline src/core/plugins/oas3/components/request-body.jsx:88]: We should create a new const, to reflect that it's a mapped value from source. Based on the changes, I would rename the above/original `examplesForMediaType`. In the case that the renamed const doesn't exist, and assign the fallback value to the (new) `examplesForMediaType`

**Review by tim-lai — CHANGES_REQUESTED** [review]

File: src/core/plugins/oas3/components/request-body.jsx (hunk 2 above)
Comment (mathis-m) [reply src/core/plugins/oas3/components/request-body.jsx:88]: Renamed old to `rawExamplesOfMediaType` and the actual example that is prepared for the media type is now named `sampleForMediaType`. I think this will clarify the meaning of the values.

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@mathis-m PR merged! Thanks for the contribution!
