### PR TITLE
fix: entries as property name

### LINKED ISSUE #6016: Field name "entries" in a schema causes swagger-ui javascript error and fails to load
- OS: ubuntu
 - Browser: chrome, firefox
 - Method of installation: python fastapi
 - Swagger-UI version: https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Problem
The openapi definition below has a schema with a field name called "entries". This causes the ui to throw a javascript error "e.entries is not a function" (see the screenshot below).

This behavior only started Friday May 15th 2020 at around 15:00 CET. Before that swagger-ui had no problems loading a schema containing a field called entries, so I am assuming something changed in the bundle I use from the url above.

Example Swagger/OpenAPI definition:
```yaml
{
  "openapi": "3.0.2",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/test/": {
      "get": {
        "summary": "Test",
        "operationId": "test_test__get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Testmodel"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Testmodel": {
        "title": "Testmodel",
        "required": [
          "name",
          "entries"
        ],
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "entries": {
            "title": "Entries",
            "type": "integer"
          }
        }
      }
    }
  }
}
```

### Screenshot

image

### To reproduce...

Try to load swagger ui using the openapi.json above

### PR DESCRIPTION
**Pull request by tim-lai**
### Description

Add a `isFunction` check to determine how to handle `js.entries`. E.g. as plain property name vs. FormData instance

### Motivation and Context

Fixes #6016 

### How Has This Been Tested?

New Cypress tests with OAS2 and OAS3.0 samples confirm proper rendering. Also confirmed multipart/form-data try-it-out still working.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/core/utils.js [hunk 1]
```diff
@@ -81,9 +82,12 @@ export function fromJSOrdered(js) {
     return Im.Seq(js).map(fromJSOrdered).toList()
   }
   if (js.entries) {
```
Comment (char0n) [inline src/core/utils.js:84]: I'd reduce the cyclomatic complexity by order of 1 into otherwise PR looks legit.
```js
if (isFunction(js.entries)) {
    // handle multipart/form-data
    const objWithHashedKeys = createObjWithHashedKeys(js)
    return Im.OrderedMap(objWithHashedKeys).map(fromJSOrdered)
} 
if (js.entries && !isFunction(js.entries)) {
   return Im.OrderedMap(js.entries).map(fromJSOrdered)
}
```
