### PR TITLE
Fixes #3500 - Fix missing names for primitive models

### LINKED ISSUE #3500: Bad schema rendering for primitive values in OAS 3.0
For OAS 3.0 rendering of primitive values (not object or array) in the schema somehow broken:
1. The schema doesn't have a name.
2. Any usages of the schema with the primitive value inside another schema leaves blank space.

Rendering screenshot: http://imgur.com/IJdpWlk

Reproducible for both swagger-editor and standalone swagger-ui.

Swagger version:
```json
{
  "swaggerEditor": "3.1.0/g66e6130-dirty",
  "swaggerUi": {
    "buildTimestamp": "Sat, 29 Jul 2017 19:20:17 GMT",
    "gitDirty": false,
    "gitRevision": "g0f7fa1f",
    "machine": "testing-gce-6bc5f0a0-dfd8-49cf-a163-82f7473df464",
    "version": "3.1.0"
  }
}
```

Minimal reproducible config:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test
paths:
  /test:
    get:
      responses:
        200:
          description: test
components:
  schemas:
    primitive:
      type: integer
      format: int64
    array-of-primitives:
      type: array
      items: 
        - $ref: '#/components/schemas/primitive'
      default: [1]
```

### PR DESCRIPTION
**Pull request by owenconti**
Fixes #3500 
Fix missing names for primitive models.

screen shot 2017-08-01 at 8 45 05 pm

screen shot 2017-08-01 at 8 47 52 pm

### CODE REVIEW

File: src/core/components/array-model.jsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ export default class ArrayModel extends Component {
   }
 
   render(){
-    let { getComponent, required, schema, depth, expandDepth, name } = this.props
```
Comment (shockey) [inline src/core/components/array-model.jsx]: Why was `required` removed?

File: src/style/_layout.scss [hunk 2]
```diff
@@ -699,7 +699,6 @@ body
 .renderedMarkdown {
   p {
     @include text_body();
-    font-size: 14px;
```
Comment (shockey) [inline src/style/_layout.scss]: Why was this removed?

File: src/core/components/array-model.jsx (hunk 1 above)
Comment (owenconti) [inline src/core/components/array-model.jsx]: `required` passed into the `<Model>` in render was hard coded to `false` and the red '*' after the model was removed because it was moved to be after the property name a couple weeks back. So the passed-in `required` prop was no longer used in the render method.

File: src/style/_layout.scss (hunk 2 above)
Comment (owenconti) [inline src/style/_layout.scss]: I wasn't 100% if the 14px was intended or not. Here's the difference:

screen shot 2017-08-01 at 9 05 09 pm

screen shot 2017-08-01 at 9 05 18 pm

**Comment by owenconti** [comment]
@webron assuming you mean the '$' beside 'int64', that is currently happening on petstore too.

**Comment by webron** [comment]
Yup, that's the $, which is why I said it's unrelated to this PR 😉
