### PR TITLE
change swagger-js wrapActions to js object

### LINKED ISSUE #7730: pluginLoadType: "chain" not working
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 96.0.4664.110
 - Method of installation: dist assets
 - Swagger-UI version: 4.1.3
 - Swagger/OpenAPI version: OpenAPI 3.0

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
    url: baseRootUrl + "/test/openapi.json",
    dom_id: '#swagger-ui',
    docExpansion: 'none',
    tagsSorter: 'alpha',
    operationsSorter: 'alpha',
    deepLinking: true,
    pluginsOptions: {pluginLoadType: "chain"},
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
    ],
    plugins: [
        CollapsibleInfoPlugin,
        ExtendedInfoPlugin
    ],
    layout: "StandaloneLayout"
});
```

### Screenshots
Screen Shot 2022-01-12 at 3 19 47 PM

### How can we help?
When I have pluginsOptions set to `pluginsOptions: {pluginLoadType: "legacy"}`, the error above does not display, but only one of my plugins works (both my plugins wrap the same component; info). I want to be able to chain load these plugins, but can't seem to do it

### PR DESCRIPTION
**Pull request by JohnBednarczyk**
Specifying for plugins to be chain loaded was causing an issue where a specific wrapActions (plugins/swagger-js) was not able to be set because the. scope of the variable was wrong.

### Description
Changing the swagger-js wrapActions to use a js object instead of the original key/value pair, which was preventing the wrapActions from being set

### Motivation and Context
Solves the problem of not being able to chain load plugins

Fixes #7730 

### How Has This Been Tested?
I haven't been able to test and will provider a comment in the issue

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
Not entirely sure about this

### CODE REVIEW

File: src/core/plugins/swagger-js/index.js [hunk 1]
```diff
@@ -30,7 +30,9 @@ export default function({ configs, getConfigs }) {
     },
     statePlugins: {
       configs: {
-        wrapActions: configsWrapActions
+        wrapActions: {
```
Comment (char0n) [inline src/core/plugins/swagger-js/index.js:33]: This is technically an invalid usage of `wrapActions` interface. The code here creates unsupported nested wrapActions object:

```js
wrapAction: {
  configsWrapActions: {
    loaded: ...implementation...
  }
}

**Review by char0n — APPROVED** [review]
Thanks for contributing! I've made a change to the PR which I explained in CR comme.
