### PR TITLE
fix: missing download button

### LINKED ISSUE #9298: Download link missing for payloads that are not application/octet-stream
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: chrome
 - Version: latest
 - Method of installation: From NSwag
 - Swagger-UI version: latest
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

This PR, https://github.com/swagger-api/swagger-ui/pull/8579/files, caused a regression for payloads that are not `application/octet-stream`.

For example, given these Response Headers:
```
Content-Disposition: attachment; filename=users.csv; filename*=UTF-8''users.csv
Content-Length: 6460682
Content-Type: text/csv
```

the type of `content` on [this line](https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/response-body.jsx#L67) is `string`, and therefore `content.size === undefined`.

### Screenshots

image

### PR DESCRIPTION
**Pull request by Omikorin**
### Description

Fixes #9298

### Motivation and Context
#9298

### How Has This Been Tested?
I've added cypress test

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by char0n** [comment]
Hi @Omikorin,

We're not passing the tests anymore with this change.

File: test/unit/components/response-body.jsx [hunk 1]
```diff
@@ -39,6 +39,13 @@ describe("<ResponseBody />", function () {
     console.warn(wrapper.debug())
     expect(wrapper.find("highlightCodeComponent[canCopy]").length).toEqual(1)
   })
+  
+  it("should render Download file link for text non-empty response", function () {
```
Comment (char0n) [inline test/unit/components/response-body.jsx:43]: This never worked before; even when https://github.com/swagger-api/swagger-ui/pull/8579 is rolled back, this test would not pass.

File: src/core/components/response-body.jsx [hunk 2]
```diff
@@ -60,11 +60,11 @@ export default class ResponseBody extends React.PureComponent {
...
-      (headers["Content-Disposition"] && /attachment/i.test(headers["Content-Disposition"])) ||
-      (headers["content-disposition"] && /attachment/i.test(headers["content-disposition"])) ||
-      (headers["Content-Description"] && /File Transfer/i.test(headers["Content-Description"])) ||
-      (headers["content-description"] && /File Transfer/i.test(headers["content-description"]))) &&
-      content.size > 0
+        (headers["Content-Disposition"] && /attachment/i.test(headers["Content-Disposition"])) ||
+        (headers["content-disposition"] && /attachment/i.test(headers["content-disposition"])) ||
+        (headers["Content-Description"] && /File Transfer/i.test(headers["Content-Description"])) ||
+        (headers["content-description"] && /File Transfer/i.test(headers["content-description"]))) &&
+      (content.size > 0 || content.length > 0)
```
Comment (char0n) [inline src/core/components/response-body.jsx:67]: Edited the predicates here to that it does what we want.

File: test/unit/components/response-body.jsx [hunk 3]
```diff
@@ -28,25 +28,33 @@ describe("<ResponseBody />", function () {
...
 
-  it("should render Download file link for non-empty response", function () {
+  it("should render Download file link for non-empty Blob response", function () {
     props.contentType = "application/octet-stream"
     props.content = new Blob(["\"test\""], { type: props.contentType })
     const wrapper = shallow(<ResponseBody {...props} />)
     expect(wrapper.text()).toMatch(/Download file/)
   })
 
+  it("should render Download file link for non-empty text response", function () {
```
Comment (char0n) [inline test/unit/components/response-body.jsx:48]: Edited the file to provide proper test that is passing against the changes in `src/

**Review by char0n — APPROVED** [review]
Thank you for issuing the PR! I've edited both the code change and test to refect the original intention in https://github.com/swagger-api/swagger-ui/issues/9298.
