### PR TITLE
[BUG-7463] Response example tabs a11y

### LINKED ISSUE #7463: Bug/Response Tabs not keyboard navigable
### Q&A (please complete the following information)
 - OS: macOS 11.5 Big Sur
 - Browser: Chrome
 - Version: 92.0.4515.131
 - Method of installation: npm
 - Swagger-UI version: 3.52.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
The tabs implementation for `Example Value` and `Schema/Model` is not keyboard navigable.

### To reproduce...

1. Navigate to https://petstore.swagger.io/ 
2. Select the endpoint labeled "Add a new pet to the store" under the "Pet" API.
3. Press `Tab` 4 times to move through the elements in order
4. On the fourth `Tab` press you will notice that the focused elements skip from the `Try it out` button to the `Parameter content type` dropdown, skipping the entire tabs section.

### Expected behavior
The fourth tab press should focus on the element labeled `Example Value`. The next `Tab` press should focus the element labeled `Schema/Model`. Pressing `Enter` or `Space` should focus the unselected tab and update the visible tabpanel accordingly.

### Screenshots
**Tab focus to Example Value**
Screen Shot 2021-08-16 at 10 26 53 AM

**Tab focus to Model**
Screen Shot 2021-08-16 at 10 27 08 AM

**Tab focus to Tabpanel section**
Screen Shot 2021-08-16 at 10 27 24 AM

### Additional context or thoughts
Aria roles and other attributes will be necessary to accommodate screen reader a11y.

### PR DESCRIPTION
**Pull request by 3ptmonster**
- Update tabs to use `<button>` elements instead of `<a>`
- Add aria roles for tablist, tabs, and tabpanel to assist with screen-reader a11y
- Replace `id`s with `data-name` attribute for tabpanels
- Create `test/e2e-cypress/tests/a11y` directory and add cypress test 7463
- Fix broken test swos-63

### Description
The tabs implementation for Example Value and Schema/Model is not keyboard navigable.

### Motivation and Context
This change is required because the implementation as it stands is not keyboard navigable, and is therefore broken for keyboard-only users. 

Fixes #7463 well as a high-priority item on [this larger a11y open issue list](https://github.com/swagger-api/swagger-ui/issues/7350).

### How Has This Been Tested?
**Environment**
OS: macOS 11.5 Big Sur
Browser(s):
- Chrome v92.0.4515.131
- Safari v14.1.2
Node version: 14.15.0
npm version: 6.14.8

I forked the master branch and ran the petstore in my local environment to test the changes. The testing consisted of keyboard-only navigation through the petstore with the macOS VoiceOver utility in both Chrome and Safari. I pressed the Tab key until I was focused on the button labeled `Example Value`, then pressed Tab a second time to ensure the focus changed to the button labeled `Model`. Once those were satisfied, the third Tab press was done to test that focus changed to the tabpanel.

### Screenshots (if appropriate):
Screen Shot 2021-08-16 at 10 26 53 AM
Screen Shot 2021-08-16 at 10 27 08 AM
Screen Shot 2021-08-16 at 10 27 24 AM

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by char0n** [comment]
Thanks @3ptmonster;

We'll get into review ASAP. I was wandering - how it is that you're familiar with swos-63 ?

**Comment by 3ptmonster** [comment]
@char0n I was not familiar with it at first, but before creating the PR I ran all the tests and it was the only one to fail, so I looked into it before making the appropriate updates.

File: src/core/components/model-example.jsx [hunk 1]
```diff
@@ -61,39 +62,58 @@ export default class ModelExample extends React.Component {
...
-      </ul>
-      <div>
-        {
-          this.state.activeTab === "example" ? (
-            example ? example : (
+    return (
+      <div className="model-example">
+        <ul className="tab" role="tablist">
+          <li className={cx("tabitem", { "active": this.state.activeTab === "example" })} role="presentation">
+            <button
```
Comment (char0n) [inline src/core/components/model-example.jsx:69]: Note: Some theory why `<button>` here replaces the `<a>` tag here: https://a11y-101.com/design/button-vs-link

File: src/core/components/model-example.jsx [hunk 2]
```diff
@@ -61,39 +62,58 @@ export default class ModelExample extends React.Component {
...
-        </li> : null }
-      </ul>
-      <div>
-        {
-          this.state.activeTab === "example" ? (
-            example ? example : (
+    return (
+      <div className="model-example">
+        <ul className="tab" role="tablist">
+          <li className={cx("tabitem", { "active": this.state.activeTab === "example" })} role="presentation">
```
Comment (char0n) [inline src/core/components/model-example.jsx:68]: Note: The presentation role is used to remove semantic meaning from an element and any of its related child elements

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_presentation_role#example_1

https://www.marcozehe.de/advanced-aria-tip-1-tabs-in-web-apps/

File: src/core/components/model-example.jsx [hunk 3]
```diff
@@ -61,39 +62,58 @@ export default class ModelExample extends React.Component {
...
+              onClick={ this.activeTab }
+              role="tab"
+            >
+              {isExecute ? "Edit Value" : "Example Value"}
+            </button>
+          </li>
+          { schema && (
+            <li className={cx("tabitem", { "active": ["model", "schema"].includes(this.state.activeTab) })} role="presentation">
+              <button
+                aria-selected={["model", "schema"].includes(this.state.activeTab)}
```
Comment (char0n) [inline src/core/components/model-example.jsx:82]: What about adding `aria-controls` attribute to buttons and `aria-labelledby` to `tabpanel`s to connect them?

https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html

File: src/core/components/model-example.jsx [hunk 4]
```diff
@@ -61,39 +62,58 @@ export default class ModelExample extends React.Component {
...
+                onClick={ this.activeTab }
+                role="tab"
+              >
+                {isOAS3 ? "Schema" : "Model" }
+              </button>
+            </li>
+          )}
+        </ul>
+        {this.state.activeTab === "example" && (
+          <div data-name="examplePanel" role="tabpanel" aria-hidden={this.state.activeTab !== "example"} tabIndex="0">
```
Comment (char0n) [inline src/core/components/model-example.jsx:94]: Instead of using data attributes here, wouldn't be more idiomatic to use `aria-labelledby` attribute?

File: src/core/components/model-example.jsx [hunk 5]
```diff
@@ -61,39 +62,58 @@ export default class ModelExample extends React.Component {
...
-                                                     includeReadOnly = {includeReadOnly}
-                                                     includeWriteOnly = {includeWriteOnly}/>
+            )}
+          </div>
+        )}
 
-
-        }
+        {["model", "schema"].includes(this.state.activeTab) && (
+          <div data-name={isOAS3 ? "schemaPanel" : "modelPanel" } role="tabpanel" aria-hidden={this.state.activeTab === "example"} tabIndex="0">
```
Comment (char0n) [inline src/core/components/model-example.jsx:102]: Instead of using data attributes here, wouldn't be more idiomatic to use `aria-labelledby` attribute?

File: test/e2e-cypress/tests/bugs/7463.js [hunk 6]
```diff
@@ -0,0 +1,35 @@
+describe("Bug-7463: Response tab elements", () => {
```
Comment (char0n) [inline test/e2e-cypress/tests/bugs/7463.js:1]: We try to break from this pattern of having `bugs/` directory. I suggest we create `test/e2e-cypress/tests/a11y` and incorporate you test there. Well continue adding test there as we progress with https://github.com/swagger-api/swagger-ui/issues/7350

**Review by char0n — CHANGES_REQUESTED** [review]
Great work!

Please have a look at my review comments and let me know if they make sense.

This PR changes `package-lock.json` file; there's not reason why it should. Can you please remove changes to `packe-lock.json` from this PR? Thanks!

File: src/core/components/model-example.jsx (hunk 3 above)
Comment (Cgfor3) [reply src/core/components/model-example.jsx:82]: I had originally included these attributes but they require ids to work properly. I would need access to additional unique variables so that each tabs section doesn't duplicate ids. If we can do that, I can add those attributes back to improve this

File: src/core/components/model-example.jsx (hunk 4 above)
Comment (Cgfor3) [reply src/core/components/model-example.jsx:94]: I'm in favor of including `aria-labelledby`, but the data-name pattern is recommended as a best practice by cypress https://docs.cypress.io/guides/references/best-practices#Selecting-Elements. If possible, I would like to include both if we can figure out how to create unique ids for the buttons and tabpanels.

File: test/e2e-cypress/tests/bugs/7463.js (hunk 6 above)
Comment (Cgfor3) [reply test/e2e-cypress/tests/bugs/7463.js:1]: Will do!

- [ ] Add a11y cypress test folder and move 7463 into that folder

**Comment by Cgfor3** [comment]
> This PR changes package-lock.json file; there's not reason why it should. Can you please remove changes to packe-lock.json from this PR? Thanks!

- [ ] Restore package-lock file from master branch

File: test/e2e-cypress/tests/a11y/7463.js [hunk 7]
```diff
@@ -0,0 +1,35 @@
+describe("Issue-7463: Response tab elements", () => {
```
Comment (char0n) [inline test/e2e-cypress/tests/a11y/7463.js:1]: Can the name of the test `test/e2e-cypress/tests/a11y/7463.js` rather describe the thing that we're testing here?

e.g. `test/e2e-cypress/tests/a11y/response-tabs.js`

Comment (char0n) [inline test/e2e-cypress/tests/a11y/7463.js:1]: The same applies for test description. Issue number is just an implementation detail that can be probably mentioned somewhere in a comment (but I don't think it's necessary)
```suggestion
describe("Response tab elements", () => {
```

File: src/core/components/model-example.jsx (hunk 5 above)
Comment (char0n) [reply src/core/components/model-example.jsx:102]: Right let's leave data attributes to decouple the testing from the JSX structure.

File: src/core/components/model-example.jsx (hunk 4 above)
Comment (char0n) [reply src/core/components/model-example.jsx:94]: > data-name pattern is recommended as a best practice by cypress https://docs.cypress.io/guides/references/best-practices#Selecting-Elements

Right, let's leave the data attributes in place and let's figure out how to use `aria-lalbelledby` attribute

File: src/core/components/model-example.jsx (hunk 3 above)
Comment (char0n) [reply src/core/components/model-example.jsx:82]: Let's deal with this in https://github.com/swagger-api/swagger-ui/pull/7464/files#r691867303

File: src/core/components/model-example.jsx (hunk 4 above)
Comment (char0n) [reply src/core/components/model-example.jsx:94]: We already use [randombytes](https://www.npmjs.com/package/randombytes) library in SwaggerUI. Let's use it to create unique ids:

```
import randomBytes from "randombytes"

const uniqueId = randomBytes(5).toString("base64")
```

Would that be enough?

Comment (3ptmonster) [reply src/core/components/model-example.jsx]: Thank you for pointing out this utility. This is enough to add the `aria-controls `and `aria-labelledby` attributes back in.

Comment (3ptmonster) [reply src/core/components/model-example.jsx]: @char0n let me know if there are any additional change requests.

**Comment by char0n** [comment]
@Cgfor3 thanks for the additional effort and work!

I'll re-review during tomorrow.

**Review by char0n — APPROVED** [review]
The functionality and test looks good! Thanks for your work on this. Before we move to merging I'll like to simplify this code if we can. 

Consider my further comments and nitpicks

File: src/core/components/model-example.jsx [hunk 8]
```diff
@@ -58,42 +60,83 @@ export default class ModelExample extends React.Component {
...
+            >
+              {isExecute ? "Edit Value" : "Example Value"}
+            </button>
+          </li>
+          { schema && (
+            <li className={cx("tabitem", { "active": ["model", "schema"].includes(this.state.activeTab) })} role="presentation">
+              <button
+                aria-controls={modelPanelId}
+                aria-selected={["model", "schema"].includes(this.state.activeTab)}
+                className={ "tablinks" + ( isExecute ? " inactive" : "" )}
```
Comment (char0n) [inline src/core/components/model-example.jsx:91]:
```suggestion
                className={cx("tablinks" { inactive: isExecute })}
```

File: src/core/components/model-example.jsx [hunk 9]
```diff
@@ -58,42 +60,83 @@ export default class ModelExample extends React.Component {
...
+                data-name={isOAS3 ? "schema" : "model"}
```
Comment (char0n) [inline src/core/components/model-example.jsx:92]: Do we actually need to distinguish here? If we would call this `schema-or-model` wouldn't this simplify the code?

Comment (3ptmonster) [reply src/core/components/model-example.jsx:92]: Yes! I wasn't sure if this was intentional so I wanted to keep everything as compatible as possible. If keeping it as one or the other would suffice just let me know what the preference is

Comment (char0n) [reply src/core/components/model-example.jsx:92]: The original code has always used `model` class and `model`  in `data-name` attribute right? Can we get the same thing here?

Comment (3ptmonster) [reply src/core/components/model-example.jsx]: All set!

**Comment by char0n** [comment]
@3ptmonster this has been a great experience collaborating with! Hope you'll keep those a11n PR comming ;]

Waiting for tests to pass and going for a merge

File: src/core/components/model-example.jsx [hunk 10]
```diff
@@ -58,42 +60,83 @@ export default class ModelExample extends React.Component {
...
-        </li> : null }
-      </ul>
-      <div>
-        {
-          this.state.activeTab === "example" ? (
-            example ? example : (
+    return (
+      <div className="model-example">
+        <ul className="tab" role="tablist">
+          <li className={cx("tabitem", { "active": this.state.activeTab === "example" })} role="presentation">
```
Comment (char0n) [inline src/core/components/model-example.jsx:73]:
```suggestion
          <li className={cx("tabitem", { active: this.state.activeTab === "example" })} role="presentation">
```

**Comment by 3ptmonster** [comment]
> @3ptmonster this has been a great experience collaborating with! Hope you'll keep those a11n PR comming ;]
> 
> Waiting for tests to pass and going for a merge

I appreciate all the help and feedback! Definitely looking forward to collaborating again.

**Comment by char0n** [comment]
@3ptmonster we have a visual regression after this PR described here: https://github.com/swagger-api/swagger-ui/pull/7517

**Comment by Cgfor3** [comment]
> @3ptmonster we have a visual regression after this PR described here: #7517

Are there documented design requirements for that call-to-action element? What would be the best way for me to assist with this regression?

**Comment by char0n** [comment]
> Are there documented design requirements for that call-to-action element? 

After the changes we made, the ideal outcome would be if the UI looked the same. I did tested it locally, but unfortunately I forgot to open the changes in Incognito Window; so the cache kicked in.

> What would be the best way for me to assist with this regression?

It's being handled in #7517 quite well. This was just FYI.
