### PR TITLE
aBug/10212 refactor unsafe components

### LINKED ISSUE #10212: Getting UNSAFE_componentWillReceiveProps error when using Next.js 15 / React 19
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome 130.0.6723.117
 - Method of installation: pnpm
 - Swagger-UI version: 5.18.2
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.1.0

### Content & configuration

I'm using a vanilla Swagger Page inside a Next.js 15 / React 19 application:

```
"use client";

import { useEffect, useState } from "react";
import SwaggerUI from "swagger-ui-react";
import "swagger-ui-react/swagger-ui.css";

function SwaggerPage() {
  const [spec, setSpec] = useState<any>(null);

  useEffect(() => {
    fetch("/api/swagger")
      .then((response) => response.json())
      .then((data) => setSpec(data));
  }, []);

  if (!spec) {
    return <div>Loading...</div>;
  }

  return <SwaggerUI spec={spec} />;
}

export default SwaggerPage;
```

### Describe the bug you're encountering

I'm seeing the following error starting in Swagger-UI `5.18.0` and continuing through `5.18.2` on my Swagger page:

```
Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://react.dev/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://react.dev/link/derived-state

Please update the following components: OperationContainer
```

### To reproduce...

1. Go to the Swagger UI page
2. Page throws an error

### Expected behavior

No error

### Screenshots

Screenshot 2024-11-11 at 10 36 22 AM

### PR DESCRIPTION
**Pull request by jryanthe4th**
### Description

`OperationContainer` changes:
- The logic from UNSAFE_componentWillReceiveProps has been moved to componentDidUpdate so swagger-ui works with react 18. 
- It checks if response has changed and updates executeInProgress accordingly. 
- It ensures that requestResolvedSubtree() is only called when isShown changes from false to true.

`ContentType` changes:
- Removed UNSAFE_componentWillReceiveProps as its logic has been handled properly in componentDidUpdate.
- componentDidUpdate now watches for changes in contentTypes or value. 
- If contentTypes change or the current value is not included, it updates the value.
- Improved readability and efficiency by ensuring onChange is only called when necessary.

`root-injects.jsx` changes:
Fix reactDOM import error:
Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".

### Motivation and Context

Swagger-ui throws errors when used with react 18 due to the deprecation of UNSAFE_componentWillReceiveProps.

https://github.com/swagger-api/swagger-ui/issues/10212

Fixes #10212 

### How Has This Been Tested?

Ran the app locally and clicked multiple links and buttons

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [x] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [ ] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by robert-hebel-sb** [comment]
@jryanthe4th thank you for your contribution and the time spent on refactoring 🙏 

A few changes are unrelated to the refactoring of unsafe components. We would appreciate it if you could create separate PRs for these, as it would make it easier to track the changes in the commit history

Addressing the ReactDOM warning would lead to the loss of support for React 16 and 17, given that the client API was introduced in React 18

File: src/core/components/content-type.jsx [hunk 1]
```diff
@@ -24,38 +23,51 @@ export default class ContentType extends React.Component {
...
+  componentDidUpdate(prevProps) {
+    const { contentTypes, value, onChange } = this.props
+
+    if (!contentTypes || !contentTypes.size) {
       return
     }
 
-    if(!nextProps.contentTypes.includes(nextProps.value)) {
-      nextProps.onChange(nextProps.contentTypes.first())
+    if (contentTypes !== prevProps.contentTypes || !contentTypes.includes(value)) {
```
Comment (glowcloud) [inline src/core/components/content-type.jsx:40]: The additional condition seems to be causing infinite re-renders, at least when testing it locally, as `contentTypes` is not of a primitive type.

```suggestion
    if (!contentTypes.includes(value)) {
```

**Review by glowcloud — CHANGES_REQUESTED** [review]
Hi @jryanthe4th,

Thanks again for the contribution! Do you plan to continue working on this PR? If so, please ensure that only changes related to this issue are included, as described in https://github.com/swagger-api/swagger-ui/pull/10373#issuecomment-2831259567. I have also left an additional comment below - please take a look at it.

File: src/core/components/content-type.jsx (hunk 1 above)
Comment (jryanthe4th) [reply src/core/components/content-type.jsx]: Thank you, I've made the changes and think I've removed everything unrelated to the issue.

File: src/core/components/content-type.jsx [hunk 2]
```diff
@@ -24,19 +23,22 @@ export default class ContentType extends React.Component {
...
+    // Populate the form initially
+    const { contentTypes, onChange } = this.props
+    if (contentTypes && contentTypes.size) {
+      onChange(contentTypes.first())
     }
   }
 
-  UNSAFE_componentWillReceiveProps(nextProps) {
-    if(!nextProps.contentTypes || !nextProps.contentTypes.size) {
+  componentDidUpdate(prevProps) {
```
Comment (glowcloud) [inline src/core/components/content-type.jsx:33]:
```suggestion
  componentDidUpdate() {
```

File: src/core/components/content-type.jsx [hunk 3]
```diff
@@ -45,7 +47,7 @@ export default class ContentType extends React.Component {
   render() {
     let { ariaControls, ariaLabel, className, contentTypes, controlId, value } = this.props
 
-    if ( !contentTypes || !contentTypes.size )
+    if (!contentTypes || !contentTypes.size)
```
Comment (glowcloud) [inline src/core/components/content-type.jsx:50]:
```suggestion
    if ( !contentTypes || !contentTypes.size )
```

**Review by glowcloud — APPROVED** [review]
Thanks for the changes! I’ve added one small fix for linting and one line revert to the previous state. Everything seems to be fine now, so LGTM!
